### ISSUE TITLE
Adding a song to the queue, replays the currently playing song

### ISSUE THREAD

**Issue by Switch123456789** [bushvin/hass-integrations#45]
I just noticed that whenever I add a track to the queue using the `media_player.play_media` Service, the currently playing song plays from the beginning.

**Comment by bushvin** [comment]
Should be fixed with v2.0.3

**Comment by Switch123456789** [comment]
Hmmm, for me it's still happening, I tested it only by adding youtube songs so far.

**Comment by bushvin** [comment]
Okay maybe it's related to the youtube extension. I know it is quirky.

Would you mind sharing the yaml service call?

**Comment by Switch123456789** [comment]
I just checked, it happens with every extension (local, mixcloud, youtube, http).
Service call:
```
service: media_player.play_media
data:
  media_content_id: youtube:video:3O1dsYURVxY
  media_content_type: music
  enqueue: add
target:
  entity_id: media_player.server_mopidy
```
