### ISSUE TITLE
Platform mopidy does not generate unique IDs. ID 192_168_0_15_6680 already exists

### ISSUE THREAD

**Issue by rtl19** [bushvin/hass-integrations#69]
Hi,
I'm running HA core 2024.5.0 in a docker container on host 192.168.0.15.  I have mopidy setup to connect to the host computer that runs the HA container on a specific IP address (192.168.0.15) .  The host computer is using Pulseaudio and is playing music directly fine (outside of mopidy).  

I added the following lines to the HA configuration.yaml file:
```
media_player:
- name: media_mopidy
  host: 192.168.0.15
  #port: 6680
  platform: mopidy
```

In HA log is the following error: 
2024-05-27 09:23:08.213 ERROR (MainThread) [homeassistant.components.media_player] Platform mopidy does not generate unique IDs. ID 192_168_0_15_6680 already exists - ignoring media_player.mopidy_server

I'm probably doing something stupid.  What am I doing wrong?
