### ISSUE TITLE
Manual configuration doesn't work

### ISSUE THREAD

**Issue by sprnza** [bushvin/hass-integrations#7]
I suppose it's due to HA moving to GUI first paradigm the manual configuration described in the README.md doesn't add `mopidy.*` services.
```
Manual Configuration

    add a media player to your home assistant configuration (<config dir>/configuration.yaml):

media_player:
- name: <mopidy identifier>
  host: <FQDN or IP address>
  port: <port if different from 6680>
  platform: mopidy
```
`media_player.mopidy` does being created but no services `mopidy.*` are becoming available. When I add the integration via GUI they does appear.
